name: Chore Master CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Env Secret
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "MONGO_URI is set: ${MONGO_URI:+YES}"
          echo "JWT_SECRET is set: ${JWT_SECRET:+YES}"
          echo "PORT is set: ${PORT:+YES}"

      - name: Stop PM2 apps if running
        run: pm2 stop all || true

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install --global yarn
          yarn --version
          yarn install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          df -h
          sudo rm -rf ./build
          yarn install
          yarn run build

      - name: Run Backend Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        working-directory: ./backend
        run: npm test

      - name: Install Root Dependencies
        run: npm ci

      - name: Create backend .env
        run: |
          cd ./backend
          touch .env
          echo "${{ secrets.PROD }}" > .env

      - name: Delete old PM2 app if exists
        run: |
          pm2 delete chore-master-backend || true

      - name: Start or Restart Backend
        run: |
          pm2 restart backend || pm2 start backend/server.js --name backend

      - name: Start or Restart Frontend
        run: |
          pm2 restart frontend || pm2 start serve --name frontend -- -s frontend/build -l 3000

      - name: Save PM2 process list
        run: pm2 save